
variables_to_use:
    tmean:
        cfs_nc_name: TMP_P0_L103_GGA0
        cfs_file_prefix: tmp2m
        prism_name: tmean
#    precip:
#        cfs_name: prpwtr
#        prism_name: prp
        
data_folder: /home/shawn/data/phenology_forecasting/

tmp_folder: /home/shawn/data/phenology_forecasting/tmp/

mask_file: land_mask.nc

season_month_begin: '11'
season_day_begin: '01'

historic_years_begin: 2008
historic_years_end: 2008

historic_observations_file: /home/shawn/data/phenology_forecasting/historic_observations.nc
historic_forecasts_file: /home/shawn/data/phenology_forecasting/historic_forecasts.nc
