
######################################################
# Global attributes

data_folder: /home/shawn/data/phenology_forecasting/

tmp_folder: tmp/

mask_file: land_mask.nc

#######################################################
# Phenology models attributes
species_range_file: species_ranges.nc

phenology_model_folder: phenology_models/

phenology_forecast_folder: phenology_forecasts/

species_list_file: species_list.csv

phenology_model_metadata_file: phenology_model_metadata.csv

phenology_observations_folder: phenology_observations/

phenology_observations_temperature_file: phenology_observations/observation_temperatures.csv

phenology_forecast_figure_folder: phenology_static_images

# prism data for building phenology models
daily_prism_folder: prism_daily_data/

# range map stuff

biolcim_folder: bioclim/

######################################################
# Climate  models attributes
variables_to_use:
    tmean:
        cfs_nc_name: TMP_P0_L103_GGA0
        cfs_file_prefix: tmp2m
        prism_name: tmean
#    precip:
#        cfs_name: prpwtr
#        prism_name: prp
        

season_month_begin: '11'
season_day_begin: '01'

historic_years_begin: 1995
historic_years_end: 2015

historic_observations_file: historic_observations.nc
historic_observations_folder: historic_observations/
historic_reanalysis_folder: historic_reanalysis/

current_season_observations_file: current_season_observations.nc

current_forecast_folder: current_forecasts/

historic_forecasts_file: historic_forecasts.nc

downscaling_model_coefficients_file: model_coefficients.nc

cfs_forecast_provenance_note: >
    CFSv2 forecast from {download_url} obtained on {today}. Downscaled to 4km
    resolution using asynchronous regression with PRISM as the observed
    temperature. Dates {season_start} to {yesterday} are observed values
    from the PRISM dataset at www.prism.oregonstate.edu. 


