
variables_to_use:
    tmean:
        cfs_name: tmp2m
        prism_name: tmean
    precip:
        cfs_name: prpwtr
        prism_name: prp
        
data_folder: /home/shawn/data/phenology_forecasting/

tmp_folder: /home/shawn/data/phenology_forecasting/tmp/

mask_file: land_mask.nc

season_month_begin: '11'
season_day_begin: '01'